export const courses = [
  {
    id: "c7f92a3e4d1b7e8f",
    title: "Modern Web Development Bootcamp",
    description:
      "Learn full-stack web development using HTML, CSS, JavaScript, Node.js, and MongoDB.",
    image:
      "https://upload.wikimedia.org/wikipedia/commons/6/61/HTML5_logo_and_wordmark.svg",
    duration: 720, // 12 hours
    level: "Beginner",
    category: "Web Development",
    tags: ["html", "css", "javascript", "nodejs", "fullstack"],
    isPublic: true,
    isFeatured: true,
    isFree: true,
    lessons: [
      {
        title: "HTML & CSS Basics",
        duration: "45 min",
        status: "completed",
        type: "video",
        link: "https://www.youtube.com/watch?v=zJSY8tbf_ys",
      },
      {
        title: "JavaScript Foundations",
        duration: "1 hour 10 min",
        status: "current",
        type: "video",
        link: "https://www.youtube.com/watch?v=cpoXLj24BDY",
      },
      {
        title: "Backend with Node.js",
        duration: "1 hour 30 min",
        status: "locked",
        type: "video",
        link: "https://www.youtube.com/watch?v=AZzV3wZCvI4",
      },
    ],
  },
  {
    id: "9z8y7x6w5v4u3t2s",
    title: "Mastering Web3 Fundamentals",
    description:
      "Dive into the core concepts of decentralized technologies, Web3 wallets, and dApp interaction.",
    image:
      "https://upload.wikimedia.org/wikipedia/commons/0/05/Ethereum_logo_2014.svg",
    duration: 540,
    level: "Intermediate",
    category: "Blockchain",
    tags: ["web3", "dapps", "wallets", "blockchain"],
    isPublic: true,
    isFeatured: true,
    isFree: false,
    lessons: [
      {
        id: "1",
        title: "Bitcoin Fundamentals",
        duration: "30 min",
        status: "completed",
        type: "video",
        link: "https://www.youtube.com/watch?v=W03_wgybrLQ",
      },
      {
        id: "2",
        title: "Ethereum and Smart Contracts",
        duration: "45 min",
        status: "current",
        type: "video",
        link: "https://www.youtube.com/watch?v=pR4Q52UxiAU",
      },
      {
        id: "3",
        title: "Building dApps",
        duration: "1 hour",
        status: "locked",
        type: "video",
        link: "https://www.youtube.com/watch?v=BDCT6TYLYdI&pp=ygUOZGFwcHMgYnVpbGRpbmc%3D",
      },
    ],
  },
  {
    id: "ab12cd34ef56gh78",
    title: "Solidity & Smart Contract Development",
    description:
      "Build and deploy smart contracts on the Ethereum blockchain using Solidity.",
    image:
      "https://upload.wikimedia.org/wikipedia/commons/9/98/Solidity_logo.svg",
    duration: 480,
    level: "Advanced",
    category: "Blockchain",
    tags: ["solidity", "ethereum", "smart contracts", "web3"],
    isPublic: true,
    isFeatured: true,
    isFree: false,
    lessons: [
      {
        id: "1",
        title: "Solidity Basics",
        duration: "40 min",
        status: "completed",
        type: "video",
        link: "https://www.youtube.com/watch?v=-1GB6m39-rM",
      },
      {
        id: "2",
        title: "Smart Contract Development",
        duration: "1 hour",
        status: "current",
        type: "video",
        link: "https://www.youtube.com/watch?v=OQl_yQyXTLU",
      },
      {
        id: "3",
        title: "What is a Smart Contract?",
        duration: "1 hour 20 min",
        status: "locked",
        type: "video",
        link: "https://www.youtube.com/watch?v=pyaIppMhuic",
      },
    ],
  },
  {
    id: "uv12wx34yz56ab78",
    title: "Introduction to Cybersecurity",
    description:
      "Understand core cybersecurity principles, ethical hacking, and network protection techniques.",
    image: "https://upload.wikimedia.org/wikipedia/commons/5/5a/OWASP_logo.svg",
    duration: 360,
    level: "Beginner",
    category: "Cybersecurity",
    tags: ["cybersecurity", "hacking", "network", "ethics"],
    isPublic: true,
    isFeatured: false,
    isFree: true,
    lessons: [
      {
        id: "1",
        title: "Cybersecurity Basics",
        duration: "30 min",
        status: "completed",
        type: "video",
        link: "https://www.youtube.com/watch?v=xtnMQKpLgcc",
      },
      {
        id: "2",
        title: "Network Security",
        duration: "45 min",
        status: "current",
        type: "video",
        link: "https://www.youtube.com/watch?v=sesacY7Xz3c&pp=ygUQbmV0d29yayBzZWN1cml0edIHCQmwCQGHKiGM7w%3D%3D",
      },
      {
        id: "3",
        title: "Ethical Hacking Introduction",
        duration: "1 hour",
        status: "locked",
        type: "video",
        link: "https://www.youtube.com/watch?v=cKEf8H9cQGM",
      },
    ],
  },
];
